CREATE DATABASE linepaydemo_2_0;

USE linepaydemo_2_0;

CREATE TABLE member
(
    memberId INT PRIMARY KEY AUTO_INCREMENT,
    memberName VARCHAR(50) NOT NULL,
    email VARCHAR(256) NOT NULL UNIQUE KEY,
    password VARCHAR(256) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);